### PR TITLE
allow upload to subdirectories

### LINKED ISSUE #12: Got error when the target server dirctory does not exist
I start this server by command `./server tmp`. Then upload a file by below command:

`curl -Ffile=@util.go 'http://localhost:25478/upload?token=b30731d81df7fc22338d'`

An error will return like this:

`{"ok":false,"error":"open tmp/util.go: no such file or directory"}`

### LINKED ISSUE #18: Upload to Subdirectory not possible
At the moment there is no upload to Subdirectories possible, uploaded files will be always stored in the root directory of /upload. If a curl with /dir/file is executed you will always get "curl: (22) The requested URL returned error: 404 "

See following examples:
curl -X PUT -k -f -Ffile=@<filename> <URL>/files/<subdir>/<filename>?token=<token>
or
curl -X POST -k -f -Ffile=@<filename> <URL>/upload/<subdir>?token=<token>

### LINKED ISSUE #26: Please support subfolder for get file
https://github.com/mayth/go-simple-upload-server/blob/09aae117513962e12600a43ee6e9d9e6de4a66d5/server.go#L38

### PR DESCRIPTION
**Pull request by execmd**
Creates subdirs if necessary on `/files/<filepath>/<filename>`

Closes #26 
Closes #18
and probably 
Closes #12

### CODE REVIEW

**Comment by binaryfire** [comment]
Would love to use this feature. Any chance of getting it merged soon @mayth? :)

**Comment by execmd** [comment]
@mayth hi. Could you please find a time to review this PR?

**Comment by execmd** [comment]
> Would love to use this feature. Any chance of getting it merged soon @mayth? :)

while its not merged, you can use my build
`docker pull execmd/go-simple-upload-server`

**Comment by cgx027** [comment]
This is exactly what I am looking for. Thanks.

**Comment by mayth** [comment]
@execmd  Thanks for your contribution.
Now v2, which is completely rewritten, supports this feature. You can upload to & get from sub directories.
I no longer maintain v1 branch except for serious security issues so close this PR.
I'm sorry that I can't write any response here.

**Pull request closed without merging**
